name: CI-Build

on:
    push:
      branches:
        - main
      paths:
        - 'src/**'
        - 'include/**'
        - 'meson.build'
    pull_request:
      branches:
        - main
      paths:
        - 'src/**'
        - 'include/**'
        - 'meson.build'

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./libfakedevice-cpp

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install meson clang

    - name: Build C++ project
      run: ./autorun.sh

  build-c:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./libfakedevice-c

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install meson clang

    - name: Build C project
      run: ./autorun.sh

  build-rust:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./libfakedevice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build Rust project
        run: |
          cargo build
