name: Deploy

on:
    push:
        branches:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install meson clang
                sudo apt install libasound2-dev

            - name: Build C++ project
              run: |
                cd libfakedevice-cpp
                ./autorun.sh

            - name: Build C project
              run: |
                cd libfakedevice-c
                ./autorun.sh

            - name: Build Rust project
              run: |
                cd libfakedevice
                ./autorun.sh

            - name: Strip C++ binary
              run: |
                strip ./binaries/fake-firmware-cpp

            - name: Strip C binary
              run: |
                strip ./binaries/fake-firmware-c

            - name: Create a release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: v1.0.0 
                files: |
                    ./binaries/fake-firmware-cpp
                    ./binaries/fake-firmware-c
                    ./binaries/fake-firmware
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}