name: Deploy

on:
    push:
        branches:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install meson clang
                sudo apt install libasound2-dev

            - name: Build C++ project
              run: |
                cd libfakedevice-cpp
                ./autorun.sh

            - name: Build C project
              run: |
                cd libfakedevice-c
                ./autorun.sh

            - name: Build Rust project
              run: |
                cd libfakedevice
                cargo build

            - name: Package artifacts
              run: |
                    mkdir -p binaries/libfakedevice_cpp
                    mkdir -p binaries/libfakedevice_c
                    mkdir -p binaries/libfakedevice_rust
                    cp -r libfakedevice-cpp/build/* binaries/libfakedevice_cpp
                    cp -r libfakedevice-c/build/* binaries/libfakedevice_c
                    cp -r libfakedevice/target/debug/* binaries/libfakedevice_rust

            - name: Create a release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: v1.0.0 
                files: |
                    ./binaries/libfakedevice_cpp
                    ./binaries/libfakedevice_c
                    ./binaries/libfakedevice_rust
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}